package modelo;
// Generated 01-jun-2024 18:23:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private Integer idRol;
     private String nombreRol;
     private Set clientes = new HashSet(0);

    public Rol() {
    }

	
    public Rol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Rol(String nombreRol, Set clientes) {
       this.nombreRol = nombreRol;
       this.clientes = clientes;
    }
   
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


