package modelo;
// Generated 05-jun-2024 0:24:16 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Habitacion generated by hbm2java
 */
public class Habitacion  implements java.io.Serializable {


     private Integer idHabitacion;
     private Hotel hotel;
     private int numero;
     private Integer piso;
     private String categoria;
     private Boolean ocupado;
     private BigDecimal precioxnoche;
     private Set reservas = new HashSet(0);

    public Habitacion() {
    }

	
    public Habitacion(int numero) {
        this.numero = numero;
    }
    public Habitacion(Hotel hotel, int numero, Integer piso, String categoria, Boolean ocupado, BigDecimal precioxnoche, Set reservas) {
       this.hotel = hotel;
       this.numero = numero;
       this.piso = piso;
       this.categoria = categoria;
       this.ocupado = ocupado;
       this.precioxnoche = precioxnoche;
       this.reservas = reservas;
    }
    
    public Habitacion(Hotel hotel, int numero, Integer piso, String categoria, Boolean ocupado, BigDecimal precioxnoche) {
       this.hotel = hotel;
       this.numero = numero;
       this.piso = piso;
       this.categoria = categoria;
       this.ocupado = ocupado;
       this.precioxnoche = precioxnoche;
    }
   
    public Integer getIdHabitacion() {
        return this.idHabitacion;
    }
    
    public void setIdHabitacion(Integer idHabitacion) {
        this.idHabitacion = idHabitacion;
    }
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public Integer getPiso() {
        return this.piso;
    }
    
    public void setPiso(Integer piso) {
        this.piso = piso;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public Boolean getOcupado() {
        return this.ocupado;
    }
    
    public void setOcupado(Boolean ocupado) {
        this.ocupado = ocupado;
    }
    public BigDecimal getPrecioxnoche() {
        return this.precioxnoche;
    }
    
    public void setPrecioxnoche(BigDecimal precioxnoche) {
        this.precioxnoche = precioxnoche;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


