package modelo;
// Generated 05-jun-2024 0:24:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hotel generated by hbm2java
 */
public class Hotel  implements java.io.Serializable {


     private Integer idHotel;
     private String nombre;
     private String direccion;
     private Integer estrellas;
     private Set habitacions = new HashSet(0);

    public Hotel() {
    }

	
    public Hotel(String nombre) {
        this.nombre = nombre;
    }
    public Hotel(String nombre, String direccion, Integer estrellas, Set habitacions) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.estrellas = estrellas;
       this.habitacions = habitacions;
    }
   
    public Integer getIdHotel() {
        return this.idHotel;
    }
    
    public void setIdHotel(Integer idHotel) {
        this.idHotel = idHotel;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getEstrellas() {
        return this.estrellas;
    }
    
    public void setEstrellas(Integer estrellas) {
        this.estrellas = estrellas;
    }
    public Set getHabitacions() {
        return this.habitacions;
    }
    
    public void setHabitacions(Set habitacions) {
        this.habitacions = habitacions;
    }




}


