package DAO;
// Generated 28-may-2024 20:31:18 by Hibernate Tools 4.3.1



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private Habitacion habitacion;
     private String nombre;
     private String email;
     private int idReserva;
     private int habitacion_1;
     private int telefono;
     private String contrasenya;

    public Cliente() {
    }

    public Cliente(Habitacion habitacion, String nombre, String email, int idReserva, int habitacion_1, int telefono, String contrasenya) {
       this.habitacion = habitacion;
       this.nombre = nombre;
       this.email = email;
       this.idReserva = idReserva;
       this.habitacion_1 = habitacion_1;
       this.telefono = telefono;
       this.contrasenya = contrasenya;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public Habitacion getHabitacion() {
        return this.habitacion;
    }
    
    public void setHabitacion(Habitacion habitacion) {
        this.habitacion = habitacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public int getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(int idReserva) {
        this.idReserva = idReserva;
    }
    public int getHabitacion_1() {
        return this.habitacion_1;
    }
    
    public void setHabitacion_1(int habitacion_1) {
        this.habitacion_1 = habitacion_1;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getContrasenya() {
        return this.contrasenya;
    }
    
    public void setContrasenya(String contrasenya) {
        this.contrasenya = contrasenya;
    }




}


