package DAO;
// Generated 28-may-2024 20:31:18 by Hibernate Tools 4.3.1



/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private Integer id;
     private Habitacion habitacion;

    public Reserva() {
    }

    public Reserva(Habitacion habitacion) {
       this.habitacion = habitacion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Habitacion getHabitacion() {
        return this.habitacion;
    }
    
    public void setHabitacion(Habitacion habitacion) {
        this.habitacion = habitacion;
    }




}


