package DAO;
// Generated 28-may-2024 20:31:18 by Hibernate Tools 4.3.1



/**
 * Trabajador generated by hbm2java
 */
public class Trabajador  implements java.io.Serializable {


     private Integer idTrabajador;
     private int nombre;
     private int email;
     private int zona;
     private String contrasenya;

    public Trabajador() {
    }

    public Trabajador(int nombre, int email, int zona, String contrasenya) {
       this.nombre = nombre;
       this.email = email;
       this.zona = zona;
       this.contrasenya = contrasenya;
    }
   
    public Integer getIdTrabajador() {
        return this.idTrabajador;
    }
    
    public void setIdTrabajador(Integer idTrabajador) {
        this.idTrabajador = idTrabajador;
    }
    public int getNombre() {
        return this.nombre;
    }
    
    public void setNombre(int nombre) {
        this.nombre = nombre;
    }
    public int getEmail() {
        return this.email;
    }
    
    public void setEmail(int email) {
        this.email = email;
    }
    public int getZona() {
        return this.zona;
    }
    
    public void setZona(int zona) {
        this.zona = zona;
    }
    public String getContrasenya() {
        return this.contrasenya;
    }
    
    public void setContrasenya(String contrasenya) {
        this.contrasenya = contrasenya;
    }




}


